### ISSUE TITLE
Inconsistent impl w/ the python & java & other langs

### ISSUE THREAD

**Issue by emaxerrno** [concord/concord-go#1]
The  get & set state are part of computation and not of context. 

https://github.com/concord/concord-go/blob/39bc138e9105c43ddc796f246fc38ffab83b7e30/service.go#L73

I like the idea on how the proxy connection is part of the comptuation object, but it should be available at for each context. You can just have a pointer passed into the constructor.

**Comment by vasilcovsky** [comment]
Fixed in https://github.com/concord/concord-go/commit/aac009b219ef647b31a6a325cc38f19ec238abe1 

However, it's still tricky to test due to:
1. State is ephemeral - if computation dies, state is getting reset
2. Concord cli doesn't support "get-state" command  yet

**Comment by vasilcovsky** [comment]
fixed in https://github.com/concord/concord-go/commit/32bbddf34c5122b90a89fca99eb4c9293dbbbd58
